
_app_blog_home:
    resource: "@AppBlogBundle/Controller/HomeController.php"
    type:     annotation

_app_blog_post:
    resource: "@AppBlogBundle/Controller/PostController.php"
    type:     annotation

