
# MYAPP
_app_blog:
    resource: "@AppBlogBundle/Controller/"
    type:     annotation

_app_base:
    resource: "@AppBaseBundle/Controller/"
    type:     annotation

# AUTH
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

# ADMIN
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin