
_app_blog_home:
    resource: "@AppBlogBundle/Controller/HomeController.php"
    type:     annotation

_app_blog_post:
    resource: "@AppBlogBundle/Controller/PostController.php"
    type:     annotation

_app_blog_category:
    resource: "@AppBlogBundle/Controller/CategoryController.php"
    type:     annotation

_app_blog_blogroll:
    resource: "@AppBlogBundle/Controller/BlogrollController.php"
    type:     annotation