
_app_blog_home:
    resource: "@AppBlogBundle/Controller/HomeController.php"
    type:     annotation

_app_blog_post:
    resource: "@AppBlogBundle/Controller/PostController.php"
    type:     annotation

_app_blog_category:
    resource: "@AppBlogBundle/Controller/CategoryController.php"
    type:     annotation

_app_blog_blogroll:
    resource: "@AppBlogBundle/Controller/BlogrollController.php"
    type:     annotation


# ADMIN BUNDLE
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
