# app/config/config.yml
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\BlogBundle\Entity\Users: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        chain_provider:
            providers: [in_memory, users_db]
        in_memory:
            users:
                lidaa: { password: lidaa, roles: 'ROLE_ADMIN' }
        users_db:
            entity: { class: App\BlogBundle\Entity\Users, property: username }

    firewalls:
        secured_area:
            pattern:    .*
            anonymous:  true
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /
                failure_path: /login?failed=1
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
